import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:open_file/open_file.dart';

class CsvExportService {
  static final _dateFormat = DateFormat('dd/MM/yyyy');
  static final _currencyFormat = NumberFormat.currency(locale: 'en_IN', symbol: '₹');

  Future<String> exportToExcel({
    required String reportType,
    required String userMobile,
    required DateTime startDate,
    required DateTime endDate,
    required dynamic data,
  }) async {
    try {
      String csvContent;
      if (reportType == 'sales' && data is List) {
        csvContent = _salesCsv(reports: data, userMobile: userMobile, startDate: startDate, endDate: endDate);
      } else if (reportType == 'purchase' && data is List) {
        csvContent = _purchaseCsv(reports: data, userMobile: userMobile, startDate: startDate, endDate: endDate);
      } else if (reportType == 'inventory' && data is List) {
        csvContent = _inventoryCsv(reports: data, userMobile: userMobile, startDate: startDate, endDate: endDate);
      } else if (reportType == 'customer' && data is List) {
        csvContent = _customerCsv(reports: data, userMobile: userMobile, startDate: startDate, endDate: endDate);
      } else if (reportType == 'supplier' && data is List) {
        csvContent = _supplierCsv(reports: data, userMobile: userMobile, startDate: startDate, endDate: endDate);
      } else {
        csvContent = _genericCsv(reportType: reportType, userMobile: userMobile,
            startDate: startDate, endDate: endDate, data: data);
      }
      return await _saveCsv(csvContent, reportType);
    } catch (e) {
      return 'Error exporting CSV: $e';
    }
  }

  Future<String> _saveCsv(String csvContent, String reportType) async {
    try {
      final directory = await getApplicationDocumentsDirectory();
      final fileName = '${reportType}_report_${DateTime.now().millisecondsSinceEpoch}.csv';
      final filePath = '${directory.path}/$fileName';
      await File(filePath).writeAsString(csvContent);
      await _openFile(filePath);
      return '✅ CSV saved successfully. Check your files.';
    } catch (e) {
      return 'Failed to save CSV file: $e';
    }
  }

  Future<void> _openFile(String filePath) async {
    final result = await OpenFile.open(filePath);
    debugPrint('Open file result: ${result.message}');
  }

  // ── CSV builders ───────────────────────────────────────────────────────────

  String _inventoryCsv({
    required List<dynamic> reports,
    required String userMobile,
    required DateTime startDate,
    required DateTime endDate,
  }) {
    double totalValue = 0;
    int lowStock = 0, outOfStock = 0;

    var csv = '"INVENTORY REPORT"\n\n'
        '"METADATA"\n'
        '"User","$userMobile"\n'
        '"Period","${formatDate(startDate)} to ${formatDate(endDate)}"\n'
        '"Generated","${formatDate(DateTime.now())}"\n\n'
        '"ITEM DETAILS"\n'
        '"Name","SKU","Category","Quantity","Price","Total Value","Status"\n';

    for (var report in reports) {
      try {
        final m = _toMap(report);
        final price = _amount(m, ['price']);
        final total = _amount(m, ['totalValue', 'total']);
        final status = _val(m, ['status']);
        totalValue += total;
        if (status.toLowerCase().contains('low')) lowStock++;
        if (status.toLowerCase().contains('out')) outOfStock++;
        csv += '"${_val(m, ['name', 'itemName'])}","${_val(m, ['sku', 'code'])}",'
            '"${_val(m, ['category'])}","${_val(m, ['quantity', 'qty'])}",'
            '"${_currencyFormat.format(price)}","${_currencyFormat.format(total)}","$status"\n';
      } catch (_) {}
    }

    final lines = csv.split('\n');
    lines.insert(5, '"Total Value","${_currencyFormat.format(totalValue)}"');
    lines.insert(6, '"Low Stock","$lowStock"');
    lines.insert(7, '"Out of Stock","$outOfStock"');
    return '${lines.join('\n')}\n"Generated by Inventory Management System"';
  }

  String _customerCsv({
    required List<dynamic> reports,
    required String userMobile,
    required DateTime startDate,
    required DateTime endDate,
  }) {
    double totalRevenue = 0, totalOutstanding = 0;

    var csv = '"CUSTOMER REPORT"\n\n'
        '"METADATA"\n'
        '"User","$userMobile"\n'
        '"Period","${formatDate(startDate)} to ${formatDate(endDate)}"\n'
        '"Generated","${formatDate(DateTime.now())}"\n\n'
        '"CUSTOMER DETAILS"\n'
        '"Name","Mobile","Total Purchases","Total Spent","Outstanding"\n';

    for (var report in reports) {
      try {
        final m = _toMap(report);
        final spent = _amount(m, ['totalSpent', 'revenue']);
        final outstanding = _amount(m, ['outstandingBalance', 'due']);
        totalRevenue += spent;
        totalOutstanding += outstanding;
        csv += '"${_val(m, ['name'])}","${_val(m, ['mobile', 'phone'])}",'
            '"${_val(m, ['totalPurchases', 'purchaseCount'])}",'
            '"${NumberFormat('#,##0.00').format(spent)}","${_currencyFormat.format(outstanding)}"\n';
      } catch (_) {}
    }

    final lines = csv.split('\n');
    lines.insert(5, '"Total Customers","${reports.length}"');
    lines.insert(6, '"Total Revenue","${_currencyFormat.format(totalRevenue)}"');
    lines.insert(7, '"Total Outstanding","${_currencyFormat.format(totalOutstanding)}"');
    return '${lines.join('\n')}\n"Generated by Inventory Management System"';
  }

  String _supplierCsv({
    required List<dynamic> reports,
    required String userMobile,
    required DateTime startDate,
    required DateTime endDate,
  }) {
    double totalPurchases = 0, totalPending = 0;

    var csv = '"SUPPLIER REPORT"\n\n'
        '"METADATA"\n'
        '"User","$userMobile"\n'
        '"Period","${formatDate(startDate)} to ${formatDate(endDate)}"\n'
        '"Generated","${formatDate(DateTime.now())}"\n\n'
        '"SUPPLIER DETAILS"\n'
        '"Name","Phone","Email","Address","Total Orders","Total Purchases","Pending Payment","Last Order"\n';

    for (var report in reports) {
      try {
        final m = _toMap(report);
        final purchases = _amount(m, ['totalPurchases']);
        final pending = _amount(m, ['pendingPayment']);
        totalPurchases += purchases;
        totalPending += pending;
        csv += '"${_val(m, ['name'])}","${_val(m, ['phone'])}","${_val(m, ['email'])}",'
            '"${_val(m, ['address'])}","${_val(m, ['totalOrders', 'orderCount'])}",'
            '"${_currencyFormat.format(purchases)}","${_currencyFormat.format(pending)}",'
            '"${_val(m, ['formattedLastOrder', 'lastOrderDate'])}"\n';
      } catch (_) {}
    }

    final lines = csv.split('\n');
    lines.insert(5, '"Total Suppliers","${reports.length}"');
    lines.insert(6, '"Total Purchases","${_currencyFormat.format(totalPurchases)}"');
    lines.insert(7, '"Total Pending","${_currencyFormat.format(totalPending)}"');
    return '${lines.join('\n')}\n"Generated by Inventory Management System"';
  }

  String _salesCsv({
    required List<dynamic> reports,
    required String userMobile,
    required DateTime startDate,
    required DateTime endDate,
  }) {
    double totalSales = 0, totalPaid = 0, totalDue = 0;
    int invoiceCount = 0;

    var csv = '"SALES REPORT"\n\n'
        '"METADATA"\n'
        '"User","$userMobile"\n'
        '"Period","${formatDate(startDate)} to ${formatDate(endDate)}"\n'
        '\n"INVOICE SUMMARY"\n'
        '"Invoice No.","Customer","Mobile","Date","Categories","Items",'
        '"Total Amount","Amount Paid","Amount Due","Status"\n';

    for (var report in reports) {
      try {
        final m = _toMap(report);
        final items = _items(m);
        final total = _amount(m, ['totalAmount', 'grandTotal', 'netAmount']);
        final paid = _amount(m, ['amountPaid', 'paidAmount', 'paid']);
        final due = _amount(m, ['amountDue', 'dueAmount', 'balance']);
        totalSales += total;
        totalPaid += paid;
        totalDue += due;
        invoiceCount++;
        csv += '"${_val(m, ['invoiceNumber', 'invoiceNo'])}","${_val(m, ['customerName', 'customer'])}",'
            '"${_val(m, ['customerMobile', 'mobile', 'phone'])}","${_val(m, ['formattedDate', 'date'])}",'
            '"${_uniqueCategories(items)}","${_itemsSummary(items)}",'
            '"${_currencyFormat.format(total)}","${_currencyFormat.format(paid)}",'
            '"${_currencyFormat.format(due)}","${_val(m, ['paymentStatus', 'status']).toUpperCase()}"\n';
      } catch (_) {}
    }

    final lines = csv.split('\n');
    lines.insert(5, '"Total Invoices","$invoiceCount"');
    lines.insert(6, '"Total Sales","${_currencyFormat.format(totalSales)}"');
    lines.insert(7, '"Total Collected","${_currencyFormat.format(totalPaid)}"');
    lines.insert(8, '"Total Due","${_currencyFormat.format(totalDue)}"');
    csv = lines.join('\n');

    csv += '\n"ITEM DETAILS"\n'
        '"Invoice No.","Item Name","Category","Quantity","Unit","Price","Total"\n';
    for (var report in reports) {
      try {
        final m = _toMap(report);
        final invoiceNo = _val(m, ['invoiceNumber', 'invoiceNo']);
        for (var item in _items(m)) {
          final im = _toMap(item);
          csv += '"$invoiceNo","${_val(im, ['name', 'productName', 'itemName'])}",'
              '"${_val(im, ['category', 'type', 'group'])}","${_val(im, ['quantity', 'qty'])}",'
              '"${_val(im, ['unit'])}","${_currencyFormat.format(_amount(im, ['price', 'unitPrice']))}",'
              '"${_currencyFormat.format(_amount(im, ['total', 'amount', 'lineTotal']))}"\n';
        }
      } catch (_) {}
    }
    return '$csv\n"Generated by Inventory Management System"';
  }

  String _purchaseCsv({
    required List<dynamic> reports,
    required String userMobile,
    required DateTime startDate,
    required DateTime endDate,
  }) {
    double totalPurchases = 0, totalPaid = 0, totalDue = 0;
    int invoiceCount = 0;

    var csv = '"PURCHASE REPORT"\n\n'
        '"METADATA"\n'
        '"User","$userMobile"\n'
        '"Period","${formatDate(startDate)} to ${formatDate(endDate)}"\n'
        '\n"INVOICE SUMMARY"\n'
        '"Invoice No.","Supplier","Mobile","Date","Categories","Items",'
        '"Total Amount","Amount Paid","Amount Due","Status"\n';

    for (var report in reports) {
      try {
        final m = _toMap(report);
        final items = _items(m);
        final total = _amount(m, ['totalAmount', 'grandTotal', 'netAmount']);
        final paid = _amount(m, ['amountPaid', 'paidAmount', 'paid']);
        final due = _amount(m, ['amountDue', 'dueAmount', 'balance']);
        totalPurchases += total;
        totalPaid += paid;
        totalDue += due;
        invoiceCount++;
        csv += '"${_val(m, ['invoiceNumber', 'invoiceNo'])}","${_val(m, ['supplierName', 'supplier'])}",'
            '"${_val(m, ['supplierMobile', 'mobile', 'phone'])}","${_val(m, ['formattedDate', 'date'])}",'
            '"${_uniqueCategories(items)}","${_itemsSummary(items)}",'
            '"${_currencyFormat.format(total)}","${_currencyFormat.format(paid)}",'
            '"${_currencyFormat.format(due)}","${_val(m, ['paymentStatus', 'status']).toUpperCase()}"\n';
      } catch (_) {}
    }

    final lines = csv.split('\n');
    lines.insert(5, '"Total Invoices","$invoiceCount"');
    lines.insert(6, '"Total Purchases","${_currencyFormat.format(totalPurchases)}"');
    lines.insert(7, '"Total Paid","${_currencyFormat.format(totalPaid)}"');
    lines.insert(8, '"Total Due","${_currencyFormat.format(totalDue)}"');
    csv = lines.join('\n');

    csv += '\n"ITEM DETAILS"\n'
        '"Invoice No.","Item Name","Category","Quantity","Unit","Price","Total"\n';
    for (var report in reports) {
      try {
        final m = _toMap(report);
        final invoiceNo = _val(m, ['invoiceNumber', 'invoiceNo']);
        for (var item in _items(m)) {
          final im = _toMap(item);
          csv += '"$invoiceNo","${_val(im, ['name', 'productName', 'itemName'])}",'
              '"${_val(im, ['category', 'type', 'group'])}","${_val(im, ['quantity', 'qty'])}",'
              '"${_val(im, ['unit'])}","${_currencyFormat.format(_amount(im, ['price', 'unitPrice']))}",'
              '"${_currencyFormat.format(_amount(im, ['total', 'amount', 'lineTotal']))}"\n';
        }
      } catch (_) {}
    }
    return '$csv\n"Generated by Inventory Management System"';
  }

  String _genericCsv({
    required String reportType,
    required String userMobile,
    required DateTime startDate,
    required DateTime endDate,
    required dynamic data,
  }) {
    final rows = _parseDataToRows(data);
    var csv = '"${reportType.toUpperCase()} REPORT"\n\n'
        '"METADATA"\n'
        '"User","$userMobile"\n'
        '"Start Date","${formatDate(startDate)}"\n'
        '"End Date","${formatDate(endDate)}"\n'
        '"Generated","${formatDate(DateTime.now())}"\n'
        '"Total Records","${rows.length}"\n\n';

    if (rows.isNotEmpty) {
      final headers = rows.first.keys.toList();
      csv += '"REPORT DATA"\n'
          '${headers.map((h) => '"${_fmtColumnName(h)}"').join(',')}\n';
      for (var row in rows) {
        csv += '${headers.map((h) => '"${_fmtCsvCell(h, row[h])}"').join(',')}\n';
      }
    } else {
      csv += '"REPORT DATA"\n"No data available for the selected period"\n';
    }
    return '$csv\n"Generated by Inventory Management System"';
  }

  // ── Shared helpers ─────────────────────────────────────────────────────────

  Map<String, dynamic> _toMap(dynamic data) {
    if (data == null) return {};
    if (data is Map<String, dynamic>) return data;
    if (data is Map) return {for (var e in data.entries) if (e.key != null) e.key.toString(): e.value};
    return {};
  }

  String _val(Map<String, dynamic> data, List<String> keys) {
    for (var k in keys) {
      if (data.containsKey(k) && data[k] != null) return data[k].toString();
    }
    return '';
  }

  double _amount(Map<String, dynamic> data, List<String> keys) {
    for (var k in keys) {
      if (data.containsKey(k) && data[k] != null) {
        try {
          if (data[k] is num) return (data[k] as num).toDouble();
          if (data[k] is String) {
            return double.tryParse(data[k].toString().replaceAll(RegExp(r'[^\d.-]'), '')) ?? 0.0;
          }
        } catch (_) {}
      }
    }
    return 0.0;
  }

  List<dynamic> _items(Map<String, dynamic> data) {
    for (var k in ['items', 'products', 'itemList', 'lineItems']) {
      if (data.containsKey(k) && data[k] is List) return data[k];
    }
    return [];
  }

  String _uniqueCategories(List<dynamic> items) {
    final cats = <String>{};
    for (var item in items) {
      final cat = _val(_toMap(item), ['category', 'type', 'group']);
      cats.add(cat.isNotEmpty ? cat : 'Uncategorized');
    }
    return cats.isEmpty ? 'No categories' : cats.join(', ');
  }

  String _itemsSummary(List<dynamic> items) {
    if (items.isEmpty) return 'No items';
    final summaries = <String>[];
    for (var item in items) {
      final m = _toMap(item);
      final name = _val(m, ['name', 'productName', 'itemName']);
      final qty = _val(m, ['quantity', 'qty', 'amount']);
      if (name.isNotEmpty && qty.isNotEmpty) summaries.add('$name ×$qty');
    }
    if (summaries.isEmpty) return '${items.length} item(s)';
    final s = summaries.join(', ');
    return s.length > 50 ? '${s.substring(0, 47)}...' : s;
  }

  List<Map<String, dynamic>> _parseDataToRows(dynamic data) {
    final rows = <Map<String, dynamic>>[];
    try {
      if (data == null) return rows;
      if (data is List) {
        for (var item in data) { if (item is Map) rows.add(Map<String, dynamic>.from(item)); }
      } else if (data is Map) {
        rows.add(Map<String, dynamic>.from(data));
      }
    } catch (_) {}
    return rows;
  }

  String _fmtColumnName(String col) => col
      .replaceAll('_', ' ')
      .replaceAllMapped(RegExp(r'[A-Z]'), (m) => ' ${m.group(0)}')
      .trim()
      .split(' ')
      .map((w) => w.isNotEmpty ? w[0].toUpperCase() + w.substring(1).toLowerCase() : '')
      .join(' ');

  String _fmtCsvCell(String column, dynamic value) {
    if (value == null) return '';
    final col = column.toLowerCase();
    if (col.contains('date') && value is String) {
      try { return formatDate(DateTime.parse(value)); } catch (_) {}
    }
    if (col.contains('amount') || col.contains('price') ||
        col.contains('total') || col.contains('value')) {
      try {
        if (value is num) return _currencyFormat.format(value);
        if (value is String) {
          final n = double.tryParse(value.replaceAll(RegExp(r'[^\d.-]'), ''));
          if (n != null) return _currencyFormat.format(n);
        }
      } catch (_) {}
    }
    if (col.contains('status')) {
      final s = value.toString().toLowerCase();
      if (s.contains('paid') || s.contains('completed')) return 'Paid';
      if (s.contains('pending') || s.contains('due')) return 'Pending';
      if (s.contains('cancel') || s.contains('void')) return 'Canceled';
    }
    return value.toString();
  }

  String formatDate(DateTime date) => _dateFormat.format(date);
}
