import 'dart:io';
import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';

/// WhatsApp sharing service.
///
/// Testing mode (no API key required):
/// - Text messages use the WhatsApp URL scheme / wa.me deep link.
/// - File sharing uses the OS share sheet — the user selects WhatsApp.
///
/// Production mode (to be wired later):
/// Replace `_sendViaApi` with WhatsApp Business API calls using the
/// stored API key and phone-number ID.
class WhatsAppService {
  WhatsAppService._();
  static final WhatsAppService instance = WhatsAppService._();

  // ── Public API ────────────────────────────────────────────────────────────

  /// Opens WhatsApp with [text] pre-filled; no specific contact.
  Future<WhatsAppResult> shareText(String text) async {
    final encoded = Uri.encodeComponent(text);
    final uri = Uri.parse('whatsapp://send?text=$encoded');
    return _launch(uri, fallback: 'https://wa.me/?text=$encoded');
  }

  /// Opens a WhatsApp chat with [phone] (include country code, e.g. 919876543210)
  /// and pre-fills [text].
  Future<WhatsAppResult> sendToNumber(String phone, String text) async {
    final clean   = phone.replaceAll(RegExp(r'[^\d]'), '');
    final encoded = Uri.encodeComponent(text);
    final uri     = Uri.parse('whatsapp://send?phone=$clean&text=$encoded');
    return _launch(uri, fallback: 'https://wa.me/$clean?text=$encoded');
  }

  /// Shares [filePath] (e.g. a PDF) via the system share sheet.
  /// The user can pick WhatsApp from the sheet.
  Future<WhatsAppResult> shareFile(
    String filePath, {
    String caption = '',
    Rect? sharePositionOrigin, // iPad / tablet positioning
  }) async {
    try {
      final file = File(filePath);
      if (!file.existsSync()) {
        return WhatsAppResult.error('File not found: $filePath');
      }
      final result = await Share.shareXFiles(
        [XFile(filePath)],
        text: caption,
        sharePositionOrigin: sharePositionOrigin,
      );
      return result.status == ShareResultStatus.success
          ? WhatsAppResult.ok()
          : WhatsAppResult.dismissed();
    } catch (e) {
      return WhatsAppResult.error(e.toString());
    }
  }

  /// Shares plain [text] via the system share sheet (not WhatsApp-specific).
  Future<WhatsAppResult> shareViaSheet(String text, {String subject = ''}) async {
    try {
      final result = await Share.share(text, subject: subject);
      return result.status == ShareResultStatus.success
          ? WhatsAppResult.ok()
          : WhatsAppResult.dismissed();
    } catch (e) {
      return WhatsAppResult.error(e.toString());
    }
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  Future<WhatsAppResult> _launch(Uri uri, {required String fallback}) async {
    try {
      if (await canLaunchUrl(uri)) {
        await launchUrl(uri);
        return WhatsAppResult.ok();
      }
      // WhatsApp not installed — fall back to wa.me web link
      final webUri = Uri.parse(fallback);
      if (await canLaunchUrl(webUri)) {
        await launchUrl(webUri, mode: LaunchMode.externalApplication);
        return WhatsAppResult.ok();
      }
      return WhatsAppResult.error('WhatsApp is not installed on this device.');
    } catch (e) {
      return WhatsAppResult.error(e.toString());
    }
  }

  // ── Message formatters ────────────────────────────────────────────────────

  /// Builds a ready-to-send invoice summary message.
  static String buildInvoiceMessage({
    required String invoiceNumber,
    required String businessName,
    required String partyName,
    required String date,
    required double totalAmount,
    required double amountPaid,
    required double amountDue,
    required String paymentStatus,
  }) {
    final statusEmoji = paymentStatus.toLowerCase() == 'paid'
        ? '✅'
        : paymentStatus.toLowerCase() == 'partial'
            ? '⏳'
            : '🔴';

    return '''
🧾 *Invoice from $businessName*

Invoice No: *$invoiceNumber*
Customer: $partyName
Date: $date

💰 Total Amount: ₹${_fmt(totalAmount)}
✅ Amount Paid:  ₹${_fmt(amountPaid)}
$statusEmoji Amount Due:   ₹${_fmt(amountDue)}

Status: *${paymentStatus.toUpperCase()}*

_This is a computer-generated invoice from Kadai._
''';
  }

  /// Builds a report summary message.
  static String buildReportMessage({
    required String reportType,
    required String period,
    required double totalAmount,
    String? extra,
  }) {
    return '''
📊 *$reportType Report*
Period: $period

Total: ₹${_fmt(totalAmount)}
${extra ?? ''}

_Generated by Kadai Inventory App_
''';
  }

  static String _fmt(double v) =>
      v.toStringAsFixed(2).replaceAllMapped(
        RegExp(r'(\d{1,3})(?=(\d{3})+(?!\d))'),
        (m) => '${m[1]},',
      );
}

// ── Result type ───────────────────────────────────────────────────────────────

enum _WhatsAppStatus { ok, dismissed, error }

class WhatsAppResult {
  final _WhatsAppStatus _status;
  final String? message;

  WhatsAppResult._(_WhatsAppStatus s, [this.message]) : _status = s;

  factory WhatsAppResult.ok()              => WhatsAppResult._(_WhatsAppStatus.ok);
  factory WhatsAppResult.dismissed()       => WhatsAppResult._(_WhatsAppStatus.dismissed);
  factory WhatsAppResult.error(String msg) => WhatsAppResult._(_WhatsAppStatus.error, msg);

  bool get isOk        => _status == _WhatsAppStatus.ok;
  bool get isDismissed => _status == _WhatsAppStatus.dismissed;
  bool get isError     => _status == _WhatsAppStatus.error;

  /// Show a snackbar feedback using [context].
  void showSnackBar(BuildContext context) {
    if (isOk || isDismissed) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message ?? 'Something went wrong'),
        backgroundColor: Theme.of(context).colorScheme.error,
        behavior: SnackBarBehavior.floating,
      ),
    );
  }
}
