// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSPMMVUQlHsQp1gHFKRxIk3CCI_gRETX4',
    appId: '1:160026269130:web:9b7285b62769e7c2c96b33',
    messagingSenderId: '160026269130',
    projectId: 'inventory-app-f65fe',
    authDomain: 'inventory-app-f65fe.firebaseapp.com',
    storageBucket: 'inventory-app-f65fe.firebasestorage.app',
    measurementId: 'G-YDT7KK6NB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVyJwMIFQtWE-sde1EMNZl-o2v7s5_4cg',
    appId: '1:160026269130:android:083c9cd3c987bff5c96b33',
    messagingSenderId: '160026269130',
    projectId: 'inventory-app-f65fe',
    storageBucket: 'inventory-app-f65fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcig9MYeolgFkzByz3eLg1gHmz3riD1-U',
    appId: '1:707917493260:ios:2b1d0e49d88167aa032a29',
    messagingSenderId: '707917493260',
    projectId: 'inventory-app-8e95c',
    storageBucket: 'inventory-app-8e95c.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcig9MYeolgFkzByz3eLg1gHmz3riD1-U',
    appId: '1:707917493260:ios:2b1d0e49d88167aa032a29',
    messagingSenderId: '707917493260',
    projectId: 'inventory-app-8e95c',
    storageBucket: 'inventory-app-8e95c.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2uOyUfYoIdLad9X-I0jCqGCMoj0bTQAs',
    appId: '1:707917493260:web:ad78adb8cf92705a032a29',
    messagingSenderId: '707917493260',
    projectId: 'inventory-app-8e95c',
    authDomain: 'inventory-app-8e95c.firebaseapp.com',
    storageBucket: 'inventory-app-8e95c.firebasestorage.app',
    measurementId: 'G-Z1R5LW6C3J',
  );
}